apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2020-12-14T07:35:29Z"
  generation: 1
  managedFields:
  - apiVersion: apiextensions.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:upbound.io/ui-schema: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"369dab72-cabd-45db-8cfe-7c7c5033d5ff"}:
            .: {}
            f:apiVersion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:conversion:
          .: {}
          f:strategy: {}
        f:group: {}
        f:names:
          f:categories: {}
          f:kind: {}
          f:listKind: {}
          f:plural: {}
          f:singular: {}
        f:scope: {}
        f:versions: {}
      f:status:
        f:acceptedNames:
          f:kind: {}
          f:plural: {}
        f:conditions: {}
        f:storedVersions: {}
    manager: crossplane
    operation: Update
    time: "2020-12-14T07:53:31Z"
  name: clusters.aws.platform.acme.io
  ownerReferences:
  - apiVersion: apiextensions.crossplane.io/v1
    controller: true
    kind: CompositeResourceDefinition
    name: compositeclusters.aws.platform.acme.io
    uid: 369dab72-cabd-45db-8cfe-7c7c5033d5ff
  resourceVersion: "21587439"
  selfLink: /apis/apiextensions.k8s.io/v1/customresourcedefinitions/clusters.aws.platform.acme.io
  uid: b11026b7-4f7e-4aa7-a5b1-4aa806e3e6d6
spec:
  conversion:
    strategy: None
  group: aws.platform.acme.io
  names:
    categories:
    - claim
    kind: Cluster
    listKind: ClusterList
    plural: clusters
    singular: cluster
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=='Ready')].status
      name: READY
      type: string
    - jsonPath: .spec.writeConnectionSecretToRef.name
      name: CONNECTION-SECRET
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: AGE
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              compositionRef:
                properties:
                  name:
                    type: string
                required:
                - name
                type: object
              compositionSelector:
                properties:
                  matchLabels:
                    additionalProperties:
                      type: string
                    type: object
                required:
                - matchLabels
                type: object
              id:
                description: ID of this Cluster that other objects will use to refer
                  to it.
                type: string
              parameters:
                description: Cluster configuration parameters.
                properties:
                  networkRef:
                    description: A reference to the Network object that this cluster
                      should be connected to.
                    properties:
                      id:
                        description: ID of the Network object this ref points to.
                        type: string
                    required:
                    - id
                    type: object
                  nodes:
                    description: Cluster node configuration parameters.
                    properties:
                      count:
                        description: Desired node count, from 1 to 100.
                        type: integer
                      size:
                        description: Size of node.
                        enum:
                        - small
                        - medium
                        - large
                        type: string
                    required:
                    - count
                    - size
                    type: object
                  services:
                    description: Services configuration parameters.
                    properties:
                      operators:
                        description: Configuration for operators.
                        properties:
                          prometheus:
                            description: Configuration for the Prometheus operator.
                            properties:
                              version:
                                description: Prometheus operator version to run.
                                type: string
                            type: object
                        type: object
                    type: object
                required:
                - nodes
                - networkRef
                type: object
              resourceRef:
                properties:
                  apiVersion:
                    type: string
                  kind:
                    type: string
                  name:
                    type: string
                required:
                - apiVersion
                - kind
                - name
                type: object
              writeConnectionSecretToRef:
                properties:
                  name:
                    type: string
                required:
                - name
                type: object
            required:
            - id
            - parameters
            type: object
          status:
            properties:
              conditions:
                description: Conditions of the resource.
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - lastTransitionTime
                  - reason
                  - status
                  - type
                  type: object
                type: array
              connectionDetails:
                properties:
                  lastPublishedTime:
                    format: date-time
                    type: string
                type: object
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    categories:
    - claim
    kind: Cluster
    listKind: ClusterList
    plural: clusters
    singular: cluster
  conditions:
  - lastTransitionTime: "2020-12-14T07:35:29Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2020-12-14T07:35:29Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2020-12-14T07:35:31Z"
  generation: 1
  managedFields:
  - apiVersion: apiextensions.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:upbound.io/ui-schema: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"8f50e7ef-dadb-4e3c-a970-a4ee5c1bea8a"}:
            .: {}
            f:apiVersion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:conversion:
          .: {}
          f:strategy: {}
        f:group: {}
        f:names:
          f:categories: {}
          f:kind: {}
          f:listKind: {}
          f:plural: {}
          f:singular: {}
        f:scope: {}
        f:versions: {}
      f:status:
        f:acceptedNames:
          f:kind: {}
          f:plural: {}
        f:conditions: {}
        f:storedVersions: {}
    manager: crossplane
    operation: Update
    time: "2020-12-14T07:53:32Z"
  name: networks.aws.platform.acme.io
  ownerReferences:
  - apiVersion: apiextensions.crossplane.io/v1
    controller: true
    kind: CompositeResourceDefinition
    name: compositenetworks.aws.platform.acme.io
    uid: 8f50e7ef-dadb-4e3c-a970-a4ee5c1bea8a
  resourceVersion: "21587456"
  selfLink: /apis/apiextensions.k8s.io/v1/customresourcedefinitions/networks.aws.platform.acme.io
  uid: 11ea509d-6b47-4c46-b8d7-c08d06c9e7cb
spec:
  conversion:
    strategy: None
  group: aws.platform.acme.io
  names:
    categories:
    - claim
    kind: Network
    listKind: NetworkList
    plural: networks
    singular: network
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=='Ready')].status
      name: READY
      type: string
    - jsonPath: .spec.writeConnectionSecretToRef.name
      name: CONNECTION-SECRET
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: AGE
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              clusterRef:
                description: A reference to the Cluster object that this network will
                  be used for.
                properties:
                  id:
                    description: ID of the Cluster object this ref points to.
                    type: string
                required:
                - id
                type: object
              compositionRef:
                properties:
                  name:
                    type: string
                required:
                - name
                type: object
              compositionSelector:
                properties:
                  matchLabels:
                    additionalProperties:
                      type: string
                    type: object
                required:
                - matchLabels
                type: object
              id:
                description: ID of this Network that other objects will use to refer
                  to it.
                type: string
              resourceRef:
                properties:
                  apiVersion:
                    type: string
                  kind:
                    type: string
                  name:
                    type: string
                required:
                - apiVersion
                - kind
                - name
                type: object
              writeConnectionSecretToRef:
                properties:
                  name:
                    type: string
                required:
                - name
                type: object
            required:
            - id
            - clusterRef
            type: object
          status:
            properties:
              conditions:
                description: Conditions of the resource.
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - lastTransitionTime
                  - reason
                  - status
                  - type
                  type: object
                type: array
              connectionDetails:
                properties:
                  lastPublishedTime:
                    format: date-time
                    type: string
                type: object
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    categories:
    - claim
    kind: Network
    listKind: NetworkList
    plural: networks
    singular: network
  conditions:
  - lastTransitionTime: "2020-12-14T07:35:31Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2020-12-14T07:35:31Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2020-12-14T07:35:32Z"
  generation: 1
  managedFields:
  - apiVersion: apiextensions.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:upbound.io/ui-schema: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"b2f8d20f-b316-47f6-98d3-46129b136279"}:
            .: {}
            f:apiVersion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:conversion:
          .: {}
          f:strategy: {}
        f:group: {}
        f:names:
          f:categories: {}
          f:kind: {}
          f:listKind: {}
          f:plural: {}
          f:singular: {}
        f:scope: {}
        f:versions: {}
      f:status:
        f:acceptedNames:
          f:kind: {}
          f:plural: {}
        f:conditions: {}
        f:storedVersions: {}
    manager: crossplane
    operation: Update
    time: "2020-12-14T07:54:01Z"
  name: postgresqlinstances.aws.platform.acme.io
  ownerReferences:
  - apiVersion: apiextensions.crossplane.io/v1
    controller: true
    kind: CompositeResourceDefinition
    name: compositepostgresqlinstances.aws.platform.acme.io
    uid: b2f8d20f-b316-47f6-98d3-46129b136279
  resourceVersion: "21587533"
  selfLink: /apis/apiextensions.k8s.io/v1/customresourcedefinitions/postgresqlinstances.aws.platform.acme.io
  uid: 728b81a9-baf1-4218-8834-591ac83bdbfc
spec:
  conversion:
    strategy: None
  group: aws.platform.acme.io
  names:
    categories:
    - claim
    kind: PostgreSQLInstance
    listKind: PostgreSQLInstanceList
    plural: postgresqlinstances
    singular: postgresqlinstance
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=='Ready')].status
      name: READY
      type: string
    - jsonPath: .spec.writeConnectionSecretToRef.name
      name: CONNECTION-SECRET
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: AGE
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              compositionRef:
                properties:
                  name:
                    type: string
                required:
                - name
                type: object
              compositionSelector:
                properties:
                  matchLabels:
                    additionalProperties:
                      type: string
                    type: object
                required:
                - matchLabels
                type: object
              parameters:
                properties:
                  networkRef:
                    description: A reference to the Network object that this postgres
                      should be connected to.
                    properties:
                      id:
                        description: ID of the Network object this ref points to.
                        type: string
                    required:
                    - id
                    type: object
                  storageGB:
                    description: GB of storage for your database
                    type: integer
                required:
                - storageGB
                - networkRef
                type: object
              resourceRef:
                properties:
                  apiVersion:
                    type: string
                  kind:
                    type: string
                  name:
                    type: string
                required:
                - apiVersion
                - kind
                - name
                type: object
              writeConnectionSecretToRef:
                properties:
                  name:
                    type: string
                required:
                - name
                type: object
            required:
            - parameters
            type: object
          status:
            properties:
              conditions:
                description: Conditions of the resource.
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - lastTransitionTime
                  - reason
                  - status
                  - type
                  type: object
                type: array
              connectionDetails:
                properties:
                  lastPublishedTime:
                    format: date-time
                    type: string
                type: object
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    categories:
    - claim
    kind: PostgreSQLInstance
    listKind: PostgreSQLInstanceList
    plural: postgresqlinstances
    singular: postgresqlinstance
  conditions:
  - lastTransitionTime: "2020-12-14T07:35:32Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2020-12-14T07:35:33Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1
